---
# # Install pre-commit hooks via
# pre-commit install

default_language_version:
  python: python3

repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.0
  hooks:
  - id: flake8
    additional_dependencies: ["flake8-bugbear"]
